# Generated by Django 3.0.3 on 2020-06-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epargne',
            name='type',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='typeOperation',
        ),
        migrations.AddField(
            model_name='commission',
            name='CpTontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Tontine'),
        ),
        migrations.AddField(
            model_name='commission',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epargne',
            name='typeCompte',
            field=models.CharField(choices=[('PHY', 'Physique'), ('MOR', 'Morale')], default='PHY', max_length=5),
        ),
        migrations.AddField(
            model_name='operation',
            name='typeOperationp',
            field=models.CharField(blank=True, choices=[('DEP', 'Depot'), ('RET', 'Retrait')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='caissier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Caissier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Operateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.CharField(blank=True, choices=[('AGT', 'Agent de Terrain'), ('SEC', 'Secretaire'), ('CAS', 'Caissier'), ('CPT', 'Comptable'), ('CTL', 'Controleur')], max_length=5, null=True),
        ),
    ]
