# Generated by Django 3.0.3 on 2020-06-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200608_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='profesion',
            new_name='profession',
        ),
    ]
