# Generated by Django 3.0.3 on 2020-06-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200609_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zoneClt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Zone', verbose_name='zone'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='dateCreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='epargne',
            name='bloque',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='epargne',
            name='clientEp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
        migrations.AlterField(
            model_name='epargne',
            name='typeCompte',
            field=models.CharField(blank=True, choices=[('PHY', 'Physique'), ('MOR', 'Morale')], default='PHY', max_length=5, null=True),
        ),
    ]
