# Generated by Django 3.0.3 on 2020-05-31 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeVirtualModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise ajour')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('numero', models.CharField(max_length=50)),
                ('solde', models.FloatField(default=0)),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='MoisCotisation',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('mise', models.FloatField(blank=True, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('montantMax', models.FloatField(blank=True, null=True)),
                ('montantActuel', models.FloatField(blank=True, null=True)),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=50)),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('addresse', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('profil', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='User/Profile', verbose_name='Image de profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(verbose_name="Date de l'operation")),
                ('typeOperation', models.CharField(max_length=50, verbose_name='Opeation')),
                ('libelle', models.CharField(max_length=50)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Operateur', to='api.Utilisateur')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MoisCotisation')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('code', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('groupe', models.CharField(max_length=50)),
                ('classe', models.IntegerField()),
                ('statut', models.CharField(max_length=50)),
                ('montantStatut', models.FloatField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Utilisateur')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=80)),
                ('dateAdhesion', models.DateField(auto_now=True)),
                ('dateNaissance', models.DateField(auto_now=True)),
                ('lieuNaissance', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=150)),
                ('profesion', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('zoneClt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Zone')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(auto_now=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('nbrb10000', models.IntegerField(verbose_name='Nombre de billets de 10.000F')),
                ('nbrb5000', models.IntegerField(verbose_name='Nombre de billets de 5.000F')),
                ('nbrb2000', models.IntegerField(verbose_name='Nombre de billets de 2.000F')),
                ('nbrb1000', models.IntegerField(verbose_name='Nombre de billets de 1.000F')),
                ('nbrb500', models.IntegerField(verbose_name='Nombre de billets de 500F')),
                ('nbrp500', models.IntegerField(verbose_name='Nombre de pieces de 500F')),
                ('nbrp250', models.IntegerField(verbose_name='Nombre de pieces de 250F')),
                ('nbrp200', models.IntegerField(verbose_name='Nombre de pieces de 200F')),
                ('nbrp100', models.IntegerField(verbose_name='Nombre de pieces de 100F')),
                ('nbrp50', models.IntegerField(verbose_name='Nombre de pieces de 50F')),
                ('nbrp25', models.IntegerField(verbose_name='Nombre de pieces de 25F')),
                ('nbrp10', models.IntegerField(verbose_name='Nombre de pieces de 10F')),
                ('nbrp5', models.IntegerField(verbose_name='Nombre de pieces de 5F')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Agent', to='api.Utilisateur')),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Caissier', to='api.Utilisateur')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Compte')),
                ('miseActuelle', models.FloatField(blank=True, null=True)),
                ('miseProchaine', models.FloatField(blank=True, null=True)),
                ('clientTont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
            bases=('api.compte',),
        ),
        migrations.CreateModel(
            name='RetraitTontine',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(blank=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('nouveauSolde', models.FloatField(blank=True, null=True)),
                ('compteTontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tontine')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.AddField(
            model_name='moiscotisation',
            name='compteTontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tontine'),
        ),
        migrations.CreateModel(
            name='Epargne',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Compte')),
                ('type', models.CharField(max_length=50)),
                ('bloque', models.BooleanField(default=None)),
                ('dateLimiteBlocage', models.DateField(blank=True, null=True)),
                ('droitAdhsion', models.FloatField(blank=True, null=True)),
                ('partSocial', models.FloatField(blank=True, null=True)),
                ('soldeInitial', models.FloatField(blank=True, null=True)),
                ('soldeBloqué', models.FloatField(blank=True, null=True)),
                ('clientEp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
            bases=('api.compte',),
        ),
    ]
