# Generated by Django 3.0.3 on 2020-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200602_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True),
        ),
    ]
