# Generated by Django 3.0.3 on 2020-06-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200608_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
