# Generated by Django 3.0.3 on 2020-06-09 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20200609_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='caissier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Caissier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrb1000',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de billets de 1.000F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrb10000',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de billets de 10.000F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrb2000',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de billets de 2.000F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrb500',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de billets de 500F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrb5000',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de billets de 5.000F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrp10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pieces de 10F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrp100',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pieces de 100F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrp200',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pieces de 200F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrp25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pieces de 25F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrp250',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pieces de 250F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrp5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pieces de 5F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrp50',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pieces de 50F'),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='nbrp500',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pieces de 500F'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateAdhesion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lieuNaissance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='zoneClt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Zone', verbose_name='zone'),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='classe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='groupe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comptecomptable',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MoisCotisation'),
        ),
        migrations.AlterField(
            model_name='moiscotisation',
            name='compteTontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tontine'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'operation"),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Operateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retraittontine',
            name='compteTontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tontine'),
        ),
        migrations.AlterField(
            model_name='timevirtualmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation'),
        ),
        migrations.AlterField(
            model_name='timevirtualmodel',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='timevirtualmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise ajour'),
        ),
        migrations.AlterField(
            model_name='tontine',
            name='clientTont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='libelle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
