# Generated by Django 3.0.3 on 2020-06-12 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20200609_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEpargne',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('nature_taux', models.CharField(blank=True, max_length=50, null=True)),
                ('taux_interet', models.FloatField(blank=True, null=True)),
                ('frais_dossier', models.FloatField(blank=True, null=True)),
                ('frais_gestion', models.FloatField(blank=True, null=True)),
                ('frais_assurance', models.FloatField(blank=True, null=True)),
                ('nbe_echeances', models.IntegerField(blank=True, null=True, verbose_name="nombre d'escheances")),
                ('duree_echeance', models.CharField(blank=True, max_length=150, null=True, verbose_name='Année/Mois/Jours')),
                ('nantissement', models.FloatField(blank=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('montant_rembourse', models.FloatField(blank=True, null=True, verbose_name='somme deja remboursé')),
                ('reste_a_rembourser', models.FloatField(blank=True, null=True, verbose_name='reste à rembourser')),
                ('rembourse', models.NullBooleanField(default=False)),
                ('prochaine_echeance', models.IntegerField(blank=True, null=True)),
                ('montant_prevue', models.FloatField(blank=True, null=True)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('agent_de_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compte_epargne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Epargne', verbose_name='Compte Epargne')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='CreditTontine',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('nature_taux', models.CharField(blank=True, max_length=50, null=True)),
                ('taux_interet', models.FloatField(blank=True, null=True)),
                ('frais_dossier', models.FloatField(blank=True, null=True)),
                ('frais_gestion', models.FloatField(blank=True, null=True)),
                ('frais_assurance', models.FloatField(blank=True, null=True)),
                ('nbe_echeances', models.IntegerField(blank=True, null=True, verbose_name="nombre d'escheances")),
                ('duree_echeance', models.CharField(blank=True, max_length=150, null=True, verbose_name='Année/Mois/Jours')),
                ('nantissement', models.FloatField(blank=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('montant_rembourse', models.FloatField(blank=True, null=True, verbose_name='somme deja remboursé')),
                ('reste_a_rembourser', models.FloatField(blank=True, null=True, verbose_name='reste à rembourser')),
                ('rembourse', models.NullBooleanField(default=False)),
                ('prochaine_echeance', models.IntegerField(blank=True, null=True)),
                ('montant_prevue', models.FloatField(blank=True, null=True)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('agent_de_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compte_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tontine', verbose_name='Compte Tontine')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='DepotEpargne',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('deposeur', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('nouveau_solde', models.FloatField(blank=True, null=True)),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='RetraitEpargne',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('receveur', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('nouveau_solde', models.FloatField(blank=True, null=True)),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='TypeCreditEpargne',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='TypeCreditTontine',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.AlterField(
            model_name='retraittontine',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='RembourssementTontine',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('montant', models.FloatField(blank=True, null=True)),
                ('interet', models.FloatField(blank=True, null=True)),
                ('penalites', models.FloatField(blank=True, default=0.0, null=True)),
                ('remboursseur', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CreditTontine')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='RembourssementEpargne',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('montant', models.FloatField(blank=True, null=True)),
                ('interet', models.FloatField(blank=True, null=True)),
                ('penalites', models.FloatField(blank=True, default=0.0, null=True)),
                ('remboursseur', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_epargne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CreditEpargne')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('date', models.DateField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DepotEpargne')),
                ('retrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RetraitEpargne')),
            ],
            bases=('api.timevirtualmodel',),
        ),
        migrations.AddField(
            model_name='credittontine',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TypeCreditEpargne', verbose_name='Type credit Epargne'),
        ),
        migrations.AddField(
            model_name='creditepargne',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TypeCreditEpargne', verbose_name='Type credit Epargne'),
        ),
        migrations.CreateModel(
            name='Amortissement',
            fields=[
                ('timevirtualmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TimeVirtualModel')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('mensualite_due', models.FloatField(blank=True, null=True)),
                ('interet_mensuel_du', models.FloatField(blank=True, null=True)),
                ('capital_mensuel_du', models.FloatField(blank=True, null=True)),
                ('solde_capital_due', models.FloatField(blank=True, null=True)),
                ('solde_mensualite_due', models.FloatField(blank=True, null=True)),
                ('rembourse', models.BooleanField(blank=True, default=False, null=True)),
                ('date_remboursement', models.DateField(blank=True, null=True)),
                ('credit_epargne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CreditEpargne')),
                ('credit_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CreditTontine')),
            ],
            bases=('api.timevirtualmodel',),
        ),
    ]
