# Generated by Django 3.0.3 on 2020-06-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_timevirtualmodel_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timevirtualmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
    ]
